In [82]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [83]:
data1 = pd.read_csv(r'E:\DS-ML-NLP\dataset\CICIDS-2017\Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv')
data2 = pd.read_csv(r'E:\DS-ML-NLP\dataset\CICIDS-2017\Friday-WorkingHours-Afternoon-PortScan.pcap_ISCX.csv')
data3=pd.read_csv(r"E:\DS-ML-NLP\dataset\CICIDS-2017\Friday-WorkingHours-Morning.pcap_ISCX.csv")
data4=pd.read_csv(r"E:\DS-ML-NLP\dataset\CICIDS-2017\Monday-WorkingHours.pcap_ISCX.csv")
data5=pd.read_csv(r"E:\DS-ML-NLP\dataset\CICIDS-2017\Thursday-WorkingHours-Afternoon-Infilteration.pcap_ISCX.csv")
data6=pd.read_csv(r"E:\DS-ML-NLP\dataset\CICIDS-2017\Thursday-WorkingHours-Morning-WebAttacks.pcap_ISCX.csv")
data7=pd.read_csv(r"E:\DS-ML-NLP\dataset\CICIDS-2017\Tuesday-WorkingHours.pcap_ISCX.csv")
data8=pd.read_csv(r"E:\DS-ML-NLP\dataset\CICIDS-2017\Wednesday-workingHours.pcap_ISCX.csv")

In [84]:

data_list = [data1, data2, data3, data4, data5, data6, data7, data8]

print('Data dimensions: ')
for i, data in enumerate(data_list, start = 1):
  rows, cols = data.shape
  print(f'Data{i} -> {rows} rows, {cols} columns')

Data dimensions:
Data1 -> 225745 rows, 79 columns
Data2 -> 286467 rows, 79 columns
Data3 -> 191033 rows, 79 columns
Data4 -> 529918 rows, 79 columns
Data5 -> 288602 rows, 79 columns
Data6 -> 170366 rows, 79 columns
Data7 -> 445909 rows, 79 columns
Data8 -> 692703 rows, 79 columns

In [85]:

data = pd.concat(data_list)
rows, cols = data.shape

print('New dimension:')
print(f'Number of rows: {rows}')
print(f'Number of columns: {cols}')
print(f'Total cells: {rows * cols}')

New dimension:
Number of rows: 2830743
Number of columns: 79
Total cells: 223628697

In [86]:
# Deleting dataframes after concating to save memory
for d in data_list: del d

In [87]:

data.columns

Index([' Destination Port', ' Flow Duration', ' Total Fwd Packets',
       ' Total Backward Packets', 'Total Length of Fwd Packets',
       ' Total Length of Bwd Packets', ' Fwd Packet Length Max',
       ' Fwd Packet Length Min', ' Fwd Packet Length Mean',
       ' Fwd Packet Length Std', 'Bwd Packet Length Max',
       ' Bwd Packet Length Min', ' Bwd Packet Length Mean',
       ' Bwd Packet Length Std', 'Flow Bytes/s', ' Flow Packets/s',
       ' Flow IAT Mean', ' Flow IAT Std', ' Flow IAT Max', ' Flow IAT Min',
       'Fwd IAT Total', ' Fwd IAT Mean', ' Fwd IAT Std', ' Fwd IAT Max',
       ' Fwd IAT Min', 'Bwd IAT Total', ' Bwd IAT Mean', ' Bwd IAT Std',
       ' Bwd IAT Max', ' Bwd IAT Min', 'Fwd PSH Flags', ' Bwd PSH Flags',
       ' Fwd URG Flags', ' Bwd URG Flags', ' Fwd Header Length',
       ' Bwd Header Length', 'Fwd Packets/s', ' Bwd Packets/s',
       ' Min Packet Length', ' Max Packet Length', ' Packet Length Mean',
       ' Packet Length Std', ' Packet Length Variance', 'FIN Flag Count',
       ' SYN Flag Count', ' RST Flag Count', ' PSH Flag Count',
       ' ACK Flag Count', ' URG Flag Count', ' CWE Flag Count',
       ' ECE Flag Count', ' Down/Up Ratio', ' Average Packet Size',
       ' Avg Fwd Segment Size', ' Avg Bwd Segment Size',
       ' Fwd Header Length.1', 'Fwd Avg Bytes/Bulk', ' Fwd Avg Packets/Bulk',
       ' Fwd Avg Bulk Rate', ' Bwd Avg Bytes/Bulk', ' Bwd Avg Packets/Bulk',
       'Bwd Avg Bulk Rate', 'Subflow Fwd Packets', ' Subflow Fwd Bytes',
       ' Subflow Bwd Packets', ' Subflow Bwd Bytes', 'Init_Win_bytes_forward',
       ' Init_Win_bytes_backward', ' act_data_pkt_fwd',
       ' min_seg_size_forward', 'Active Mean', ' Active Std', ' Active Max',
       ' Active Min', 'Idle Mean', ' Idle Std', ' Idle Max', ' Idle Min',
       ' Label'],
      dtype='object')

In [88]:

data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2830743 entries, 0 to 692702
Data columns (total 79 columns):
 #   Column                        Dtype
---  ------                        -----
 0    Destination Port             int64
 1    Flow Duration                int64
 2    Total Fwd Packets            int64
 3    Total Backward Packets       int64
 4   Total Length of Fwd Packets   int64
 5    Total Length of Bwd Packets  int64
 6    Fwd Packet Length Max        int64
 7    Fwd Packet Length Min        int64
 8    Fwd Packet Length Mean       float64
 9    Fwd Packet Length Std        float64
 10  Bwd Packet Length Max         int64
 11   Bwd Packet Length Min        int64
 12   Bwd Packet Length Mean       float64
 13   Bwd Packet Length Std        float64
 14  Flow Bytes/s                  float64
 15   Flow Packets/s               float64
 16   Flow IAT Mean                float64
 17   Flow IAT Std                 float64
 18   Flow IAT Max                 int64
 19   Flow IAT Min                 int64
 20  Fwd IAT Total                 int64
 21   Fwd IAT Mean                 float64
 22   Fwd IAT Std                  float64
 23   Fwd IAT Max                  int64
 24   Fwd IAT Min                  int64
 25  Bwd IAT Total                 int64
 26   Bwd IAT Mean                 float64
 27   Bwd IAT Std                  float64
 28   Bwd IAT Max                  int64
 29   Bwd IAT Min                  int64
 30  Fwd PSH Flags                 int64
 31   Bwd PSH Flags                int64
 32   Fwd URG Flags                int64
 33   Bwd URG Flags                int64
 34   Fwd Header Length            int64
 35   Bwd Header Length            int64
 36  Fwd Packets/s                 float64
 37   Bwd Packets/s                float64
 38   Min Packet Length            int64
 39   Max Packet Length            int64
 40   Packet Length Mean           float64
 41   Packet Length Std            float64
 42   Packet Length Variance       float64
 43  FIN Flag Count                int64
 44   SYN Flag Count               int64
 45   RST Flag Count               int64
 46   PSH Flag Count               int64
 47   ACK Flag Count               int64
 48   URG Flag Count               int64
 49   CWE Flag Count               int64
 50   ECE Flag Count               int64
 51   Down/Up Ratio                int64
 52   Average Packet Size          float64
 53   Avg Fwd Segment Size         float64
 54   Avg Bwd Segment Size         float64
 55   Fwd Header Length.1          int64
 56  Fwd Avg Bytes/Bulk            int64
 57   Fwd Avg Packets/Bulk         int64
 58   Fwd Avg Bulk Rate            int64
 59   Bwd Avg Bytes/Bulk           int64
 60   Bwd Avg Packets/Bulk         int64
 61  Bwd Avg Bulk Rate             int64
 62  Subflow Fwd Packets           int64
 63   Subflow Fwd Bytes            int64
 64   Subflow Bwd Packets          int64
 65   Subflow Bwd Bytes            int64
 66  Init_Win_bytes_forward        int64
 67   Init_Win_bytes_backward      int64
 68   act_data_pkt_fwd             int64
 69   min_seg_size_forward         int64
 70  Active Mean                   float64
 71   Active Std                   float64
 72   Active Max                   int64
 73   Active Min                   int64
 74  Idle Mean                     float64
 75   Idle Std                     float64
 76   Idle Max                     int64
 77   Idle Min                     int64
 78   Label                        object
dtypes: float64(24), int64(54), object(1)
memory usage: 1.7+ GB

## Data Cleaning

In [89]:
dups = data[data.duplicated()]
print(f'Number of duplicates: {len(dups)}')

Number of duplicates: 308381

In [90]:
data.drop_duplicates(inplace = True)
data.shape

(2522362, 79)

In [91]:
data.head(10)

,Destination Port,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,54865,3,2,0,12,0,6,6,6.0,0.00000,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
1,55054,109,1,1,6,6,6,6,6.0,0.00000,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
2,55055,52,1,1,6,6,6,6,6.0,0.00000,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
3,46236,34,1,1,6,6,6,6,6.0,0.00000,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
4,54863,3,2,0,12,0,6,6,6.0,0.00000,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
5,54871,1022,2,0,12,0,6,6,6.0,0.00000,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
6,54925,4,2,0,12,0,6,6,6.0,0.00000,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
7,54925,42,1,1,6,6,6,6,6.0,0.00000,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
8,9282,4,2,0,12,0,6,6,6.0,0.00000,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
9,55153,4,2,0,37,0,31,6,18.5,17.67767,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN

In [92]:
# Per column
(data.isnull().sum() / len(data)) * 100

# As a DataFrame
missing_data = pd.DataFrame({
    'Missing_Count': data.isnull().sum(),
    'Missing_Percent': (data.isnull().sum() / len(data)) * 100
})
missing_data

                             Missing_Count  Missing_Percent
 Destination Port                        0              0.0
 Flow Duration                           0              0.0
 Total Fwd Packets                       0              0.0
 Total Backward Packets                  0              0.0
Total Length of Fwd Packets              0              0.0
...                                    ...              ...
Idle Mean                                0              0.0
 Idle Std                                0              0.0
 Idle Max                                0              0.0
 Idle Min                                0              0.0
 Label                                   0              0.0

[79 rows x 2 columns]

In [93]:
# Clean column names first
data.columns = data.columns.str.strip()

# Now try again
med_flow_bytes = data['Flow Bytes/s'].median()
med_flow_packets = data['Flow Packets/s'].median()  # Should work now

print('Median of Flow Bytes/s:', med_flow_bytes)
print('Median of Flow Packets/s:', med_flow_packets)

Median of Flow Bytes/s: 3722.028051
Median of Flow Packets/s: 70.08936394

In [94]:
data['Flow Bytes/s'] = data['Flow Bytes/s'].fillna(med_flow_bytes)
data['Flow Packets/s'] = data['Flow Packets/s'].fillna(med_flow_packets)

In [95]:
print('Number of \'Flow Bytes/s\' missing values:', data['Flow Bytes/s'].isna().sum())
print('Number of \'Flow Packets/s\' missing values:', data['Flow Packets/s'].isna().sum())

Number of 'Flow Bytes/s' missing values: 0
Number of 'Flow Packets/s' missing values: 0

In [96]:
data['Label'].unique()

array(['BENIGN', 'DDoS', 'PortScan', 'Bot', 'Infiltration',
       'Web Attack � Brute Force', 'Web Attack � XSS',
       'Web Attack � Sql Injection', 'FTP-Patator', 'SSH-Patator',
       'DoS slowloris', 'DoS Slowhttptest', 'DoS Hulk', 'DoS GoldenEye',
       'Heartbleed'], dtype=object)

In [97]:

# Types of attacks & normal instances (BENIGN)
data['Label'].value_counts()

Label
BENIGN                        2096484
DoS Hulk                       172849
DDoS                           128016
PortScan                        90819
DoS GoldenEye                   10286
FTP-Patator                      5933
DoS slowloris                    5385
DoS Slowhttptest                 5228
SSH-Patator                      3219
Bot                              1953
Web Attack � Brute Force         1470
Web Attack � XSS                  652
Infiltration                       36
Web Attack � Sql Injection         21
Heartbleed                         11
Name: count, dtype: int64

In [98]:
attack_map = {
    'BENIGN': 'BENIGN',
    'DDoS': 'DDoS',
    'DoS Hulk': 'DoS',
    'DoS GoldenEye': 'DoS',
    'DoS slowloris': 'DoS',
    'DoS Slowhttptest': 'DoS',
    'PortScan': 'Port Scan',
    'FTP-Patator': 'Brute Force',
    'SSH-Patator': 'Brute Force',
    'Bot': 'Bot',
    'Web Attack � Brute Force': 'Web Attack',
    'Web Attack � XSS': 'Web Attack',
    'Web Attack � Sql Injection': 'Web Attack',
    'Infiltration': 'Infiltration',
    'Heartbleed': 'Heartbleed'
}

# Creating a new column 'Attack Type' in the DataFrame based on the attack_map dictionary
data['Attack Type'] = data['Label'].map(attack_map)

In [99]:
data['Attack Type'].value_counts()

Attack Type
BENIGN          2096484
DoS              193748
DDoS             128016
Port Scan         90819
Brute Force        9152
Web Attack         2143
Bot                1953
Infiltration         36
Heartbleed           11
Name: count, dtype: int64

In [100]:
data.drop('Label', axis = 1, inplace = True)

In [101]:

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
data['Attack Number'] = le.fit_transform(data['Attack Type'])

print(data['Attack Number'].unique())

[0 3 7 1 6 8 2 4 5]

In [102]:
outlier_summary = []

for col in data.select_dtypes(include=np.number).columns:
    
    Q1 = data[col].quantile(0.25)
    Q3 = data[col].quantile(0.75)
    IQR = Q3 - Q1
    
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    
    outliers = data[(data[col] < lower) | (data[col] > upper)]
    
    count = outliers.shape[0]
    percent = (count / len(data)) * 100
    
    outlier_summary.append([col, count, percent])

outlier_df = pd.DataFrame(outlier_summary, columns=["Feature", "Outlier Count", "Outlier %"])

print(outlier_df)

                        Feature  Outlier Count  Outlier %
0              Destination Port         546849  21.680036
1                 Flow Duration         468223  18.562879
2             Total Fwd Packets         253005  10.030479
3        Total Backward Packets         239223   9.484087
4   Total Length of Fwd Packets         315337  12.501655
..                          ...            ...        ...
74                    Idle Mean         567235  22.488247
75                     Idle Std         229243   9.088426
76                     Idle Max         567235  22.488247
77                     Idle Min         567235  22.488247
78                Attack Number         425878  16.884095

[79 rows x 3 columns]

In [103]:

skewness = data.select_dtypes(include=np.number).skew()

skew_df = skewness.reset_index()
skew_df.columns = ["Feature", "Skewness"]

print(skew_df)

e:\DS-ML-NLP\venv\Lib\site-packages\pandas\core\nanops.py:1256: RuntimeWarning: invalid value encountered in subtract
  adjusted = values - mean

                        Feature    Skewness
0              Destination Port    1.930838
1                 Flow Duration    1.965036
2             Total Fwd Packets  230.686315
3        Total Backward Packets  230.968239
4   Total Length of Fwd Packets  760.815157
..                          ...         ...
74                    Idle Mean    2.842728
75                     Idle Std    9.889364
76                     Idle Max    2.732715
77                     Idle Min    2.956702
78                Attack Number    2.356496

[79 rows x 2 columns]

In [104]:
# Dropping columns with only one unique value
num_unique = data.nunique()
one_variable = num_unique[num_unique == 1]
not_one_variable = num_unique[num_unique > 1].index

dropped_cols = one_variable.index
data = data[not_one_variable]

print('Dropped columns:')
dropped_cols

Dropped columns:

Index(['Bwd PSH Flags', 'Bwd URG Flags', 'Fwd Avg Bytes/Bulk',
       'Fwd Avg Packets/Bulk', 'Fwd Avg Bulk Rate', 'Bwd Avg Bytes/Bulk',
       'Bwd Avg Packets/Bulk', 'Bwd Avg Bulk Rate'],
      dtype='object')

In [105]:
data.duplicated().sum()

np.int64(0)

In [119]:


features = data.drop(columns=['Attack Type'])
target = data['Attack Type']

# replace infinity
features.replace([np.inf, -np.inf], np.nan, inplace=True)

# fill missing values
features.fillna(features.median(), inplace=True)

In [120]:
np.isinf(features).sum().sum()

np.int64(0)

In [121]:


inf_counts = np.isinf(features).sum()
inf_counts = inf_counts[inf_counts > 0]

print(inf_counts)

Series([], dtype: int64)

In [122]:
features.replace([np.inf, -np.inf], np.nan, inplace=True)

In [123]:
np.isinf(features).sum().sum()

np.int64(0)

In [124]:
features.fillna(features.median(), inplace=True)

In [125]:
print("NaN values:", features.isna().sum().sum())
print("Inf values:", np.isinf(features).sum().sum())

NaN values: 0
Inf values: 0

In [126]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaled_features = scaler.fit_transform(features)

In [127]:

from sklearn.decomposition import IncrementalPCA

size = len(features.columns) // 2
ipca = IncrementalPCA(n_components = size, batch_size = 500)
for batch in np.array_split(scaled_features, len(features) // 500):
    ipca.partial_fit(batch)

print(f'information retained: {sum(ipca.explained_variance_ratio_):.2%}')

information retained: 99.10%

In [128]:
transformed_features = ipca.transform(scaled_features)
new_data = pd.DataFrame(transformed_features, columns = [f'PC{i+1}' for i in range(size)])
new_data['Attack Type'] = attacks.values

In [129]:

new_data

,PC1,PC2,PC3,PC4,PC5,PC6,PC7,PC8,PC9,PC10,...,PC27,PC28,PC29,PC30,PC31,PC32,PC33,PC34,PC35,Attack Type
0,-2.342624,-0.052298,0.504211,0.485507,3.855629,0.348871,-0.019741,0.188815,0.403044,-0.684848,...,0.301605,-0.057750,0.708267,-0.519851,-0.019738,0.019368,0.001561,0.089105,0.145161,BENIGN
1,-2.280414,-0.048420,0.464075,0.326280,2.010696,-0.160659,-0.016288,-0.782336,-0.877113,2.642360,...,0.637541,0.264713,0.424668,0.777337,0.226709,-0.056356,0.001445,0.039094,-0.018781,BENIGN
2,-2.292376,-0.048803,0.468996,0.335508,2.091590,-0.152980,-0.016553,-0.771036,-0.865295,2.616471,...,0.626067,0.248296,0.427604,0.774363,0.221421,-0.054006,0.001442,0.038152,-0.021474,BENIGN
3,-2.282338,-0.050015,0.461216,0.275313,2.022544,-0.126161,-0.015992,-0.746451,-0.828858,2.490310,...,0.488461,0.135361,0.100183,0.796994,0.090680,0.006605,0.001280,0.022889,0.004346,BENIGN
4,-2.342620,-0.052299,0.504213,0.485486,3.855599,0.348862,-0.019743,0.188801,0.403066,-0.684864,...,0.301563,-0.057790,0.708199,-0.519829,-0.019775,0.019384,0.001561,0.089107,0.145174,BENIGN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2522357,-2.002105,-0.034293,0.215145,-0.508477,-0.745879,-0.260385,-0.029428,-0.394606,0.264339,-0.400787,...,0.089078,-0.321227,-0.017901,0.285133,-0.084826,-0.043931,0.000846,0.015571,-0.485899,BENIGN
2522358,-2.003812,-0.034309,0.146135,-0.690542,-1.381123,-1.054007,-0.085223,-0.674130,1.057300,-0.344313,...,0.230412,0.277693,0.074158,0.004461,-0.385691,-0.388294,-0.003343,-0.000363,-0.006038,BENIGN
2522359,-2.215530,-0.042031,0.885478,1.141549,4.486869,0.088072,-0.038381,0.681737,1.508917,-0.913415,...,0.321112,0.293444,1.480825,-0.105217,0.649590,-0.199997,0.001087,0.136220,-0.117175,BENIGN
2522360,-1.943403,-0.035095,0.240121,-0.593804,-0.954136,-0.485936,-0.048465,-0.495453,0.547120,-0.471108,...,0.354063,-0.069318,0.048468,0.366050,-0.337158,-0.278711,-0.001197,0.018488,-0.324749,BENIGN
2522361,-2.018301,-0.032571,0.245381,-0.531367,-1.089054,-0.680130,-0.061062,-0.528930,0.728409,-0.499054,...,0.449564,-0.128264,0.015266,0.395980,0.005526,0.097427,0.002578,0.035713,-0.229780,BENIGN

In [135]:

class_counts = new_data['Attack Type'].value_counts()
selected_classes = class_counts[class_counts > 1950]
class_names = selected_classes.index
selected = new_data[new_data['Attack Type'].isin(class_names)]

dfs = []
for name in class_names:
  df = selected[selected['Attack Type'] == name]
  if len(df) > 2500:
    df = df.sample(n = 5000, random_state = 0)

  dfs.append(df)

df = pd.concat(dfs, ignore_index = True)
df['Attack Type'].value_counts()

Attack Type
BENIGN         5000
DoS            5000
DDoS           5000
Port Scan      5000
Brute Force    5000
Web Attack     2143
Bot            1953
Name: count, dtype: int64

In [137]:
!pip install imbalanced-learn

Collecting imbalanced-learn
  Downloading imbalanced_learn-0.14.1-py3-none-any.whl.metadata (8.9 kB)
Requirement already satisfied: numpy<3,>=1.25.2 in e:\ds-ml-nlp\venv\lib\site-packages (from imbalanced-learn) (2.3.2)
Requirement already satisfied: scipy<2,>=1.11.4 in e:\ds-ml-nlp\venv\lib\site-packages (from imbalanced-learn) (1.16.1)
Requirement already satisfied: scikit-learn<2,>=1.4.2 in e:\ds-ml-nlp\venv\lib\site-packages (from imbalanced-learn) (1.7.1)
Collecting sklearn-compat<0.2,>=0.1.5 (from imbalanced-learn)
  Downloading sklearn_compat-0.1.5-py3-none-any.whl.metadata (20 kB)
Requirement already satisfied: joblib<2,>=1.2.0 in e:\ds-ml-nlp\venv\lib\site-packages (from imbalanced-learn) (1.5.1)
Requirement already satisfied: threadpoolctl<4,>=2.0.0 in e:\ds-ml-nlp\venv\lib\site-packages (from imbalanced-learn) (3.6.0)
Downloading imbalanced_learn-0.14.1-py3-none-any.whl (235 kB)
Downloading sklearn_compat-0.1.5-py3-none-any.whl (20 kB)
Installing collected packages: sklearn-compat, imbalanced-learn

   ---------------------------------------- 0/2 [sklearn-compat]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   ---------------------------------------- 2/2 [imbalanced-learn]

Successfully installed imbalanced-learn-0.14.1 sklearn-compat-0.1.5

In [141]:
from imblearn.over_sampling import SMOTE



X = df.drop('Attack Type', axis=1)
y = df['Attack Type']
smote = SMOTE(sampling_strategy='auto', random_state=0)
X_upsampled, y_upsampled = smote.fit_resample(X, y)
blnc_data = pd.DataFrame(X_upsampled)
blnc_data['Attack Type'] = y_upsampled
blnc_data = blnc_data.sample(frac=1)
blnc_data['Attack Type'].value_counts()

Attack Type
DDoS           5000
DoS            5000
Brute Force    5000
Bot            5000
BENIGN         5000
Web Attack     5000
Port Scan      5000
Name: count, dtype: int64

In [157]:
from sklearn.model_selection import train_test_split
features = blnc_data.drop('Attack Type', axis = 1)
labels = blnc_data['Attack Type']

X_train, X_test, y_train, y_test = train_test_split(features, labels, test_size = 0.25, random_state = 0)

In [150]:
from sklearn.model_selection import cross_val_score

from sklearn.tree import DecisionTreeClassifier

dt1 = DecisionTreeClassifier(max_depth = 6)
dt1.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=6)

In [149]:
cv_dt1 = cross_val_score(dt1, X_train, y_train, cv = 5)
print('Decision Tree Model 1')
print(f'\nCross-validation scores:', ', '.join(map(str, cv_dt1)))
print(f'\nMean cross-validation score: {cv_dt1.mean():.2f}')

Decision Tree Model 1

Cross-validation scores: 0.9573333333333334, 0.9537142857142857, 0.9619047619047619, 0.9605714285714285, 0.9527619047619048

Mean cross-validation score: 0.96

In [147]:

from sklearn.tree import DecisionTreeClassifier

dt1 = DecisionTreeClassifier(max_depth = 6)
dt1.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=6)

In [148]:
cv_dt1 = cross_val_score(dt1, X_train, y_train, cv = 5)
print('Decision Tree Model 1')
print(f'\nCross-validation scores:', ', '.join(map(str, cv_dt1)))
print(f'\nMean cross-validation score: {cv_dt1.mean():.2f}')

Decision Tree Model 1

Cross-validation scores: 0.9573333333333334, 0.9539047619047619, 0.9619047619047619, 0.96, 0.952952380952381

Mean cross-validation score: 0.96

In [152]:
from sklearn.neighbors import KNeighborsClassifier

knn1 = KNeighborsClassifier(n_neighbors = 16)
knn1.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=16)

In [153]:
cv_knn1 = cross_val_score(knn1, X_train, y_train, cv = 5)
print('K Nearest Neighbors Model 1')
print(f'\nCross-validation scores:', ', '.join(map(str, cv_knn1)))
print(f'\nMean cross-validation score: {cv_knn1.mean():.2f}')

K Nearest Neighbors Model 1

Cross-validation scores: 0.989904761904762, 0.9883809523809524, 0.9897142857142858, 0.9908571428571429, 0.9874285714285714

Mean cross-validation score: 0.99