In [164]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [165]:
data1 = pd.read_csv(r'E:\DS-ML-NLP\dataset\CICIDS-2017\Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv')
data2 = pd.read_csv(r'E:\DS-ML-NLP\dataset\CICIDS-2017\Friday-WorkingHours-Afternoon-PortScan.pcap_ISCX.csv')
data3=pd.read_csv(r"E:\DS-ML-NLP\dataset\CICIDS-2017\Friday-WorkingHours-Morning.pcap_ISCX.csv")
data4=pd.read_csv(r"E:\DS-ML-NLP\dataset\CICIDS-2017\Monday-WorkingHours.pcap_ISCX.csv")
data5=pd.read_csv(r"E:\DS-ML-NLP\dataset\CICIDS-2017\Thursday-WorkingHours-Afternoon-Infilteration.pcap_ISCX.csv")
data6=pd.read_csv(r"E:\DS-ML-NLP\dataset\CICIDS-2017\Thursday-WorkingHours-Morning-WebAttacks.pcap_ISCX.csv")
data7=pd.read_csv(r"E:\DS-ML-NLP\dataset\CICIDS-2017\Tuesday-WorkingHours.pcap_ISCX.csv")
data8=pd.read_csv(r"E:\DS-ML-NLP\dataset\CICIDS-2017\Wednesday-workingHours.pcap_ISCX.csv")

In [166]:

data_list = [data1, data2, data3, data4, data5, data6, data7, data8]

print('Data dimensions: ')
for i, data in enumerate(data_list, start = 1):
  rows, cols = data.shape
  print(f'Data{i} -> {rows} rows, {cols} columns')

Data dimensions:
Data1 -> 225745 rows, 79 columns
Data2 -> 286467 rows, 79 columns
Data3 -> 191033 rows, 79 columns
Data4 -> 529918 rows, 79 columns
Data5 -> 288602 rows, 79 columns
Data6 -> 170366 rows, 79 columns
Data7 -> 445909 rows, 79 columns
Data8 -> 692703 rows, 79 columns

In [167]:

data = pd.concat(data_list)
rows, cols = data.shape

print('New dimension:')
print(f'Number of rows: {rows}')
print(f'Number of columns: {cols}')
print(f'Total cells: {rows * cols}')

New dimension:
Number of rows: 2830743
Number of columns: 79
Total cells: 223628697

In [168]:
# Deleting dataframes after concating to save memory
for d in data_list: del d

In [201]:
data

,Destination Port,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Attack Type
286742,80,98875691,8,5,349,11595,343,0,43.625000,120.983987,...,20,9.880000e+02,0.00000,988,988,9.890000e+07,0.00000,98900000,98900000,DoS
278990,443,19025729,10,6,980,3990,613,0,98.000000,196.377754,...,32,7.098720e+05,0.00000,709872,709872,9.960012e+06,0.00000,9960012,9960012,BENIGN
78122,53,56023456,2,2,111,421,56,55,55.500000,0.707107,...,20,1.216080e+05,0.00000,121608,121608,5.587100e+07,0.00000,55870999,55870999,BENIGN
273290,80,98131731,5,7,327,11595,315,0,65.400000,139.562889,...,20,1.698000e+03,0.00000,1698,1698,9.800000e+07,0.00000,98000000,98000000,DoS
97625,80,99468760,7,7,381,11595,363,0,54.428571,136.100278,...,20,1.399300e+04,0.00000,13993,13993,9.830000e+07,0.00000,98300000,98300000,DoS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6651,53,30973,2,2,90,210,45,45,45.000000,0.000000,...,32,0.000000e+00,0.00000,0,0,0.000000e+00,0.00000,0,0,BENIGN
97986,80,81647011,8,5,56,11607,20,0,7.000000,5.656854,...,20,4.079578e+06,0.00000,4079578,4079578,7.620000e+07,0.00000,76200000,76200000,DDoS
148386,3006,54,1,1,0,6,0,0,0.000000,0.000000,...,40,0.000000e+00,0.00000,0,0,0.000000e+00,0.00000,0,0,Port Scan
249344,80,115972484,17,15,519,1598,435,0,30.529412,104.248572,...,20,5.905145e+04,81600.82162,305087,34355,9.990339e+06,71471.19451,10000000,9774845,BENIGN
124590,53,51330,1,1,47,109,47,47,47.000000,0.000000,...,32,0.000000e+00,0.00000,0,0,0.000000e+00,0.00000,0,0,BENIGN

In [169]:

data.columns

Index([' Destination Port', ' Flow Duration', ' Total Fwd Packets',
       ' Total Backward Packets', 'Total Length of Fwd Packets',
       ' Total Length of Bwd Packets', ' Fwd Packet Length Max',
       ' Fwd Packet Length Min', ' Fwd Packet Length Mean',
       ' Fwd Packet Length Std', 'Bwd Packet Length Max',
       ' Bwd Packet Length Min', ' Bwd Packet Length Mean',
       ' Bwd Packet Length Std', 'Flow Bytes/s', ' Flow Packets/s',
       ' Flow IAT Mean', ' Flow IAT Std', ' Flow IAT Max', ' Flow IAT Min',
       'Fwd IAT Total', ' Fwd IAT Mean', ' Fwd IAT Std', ' Fwd IAT Max',
       ' Fwd IAT Min', 'Bwd IAT Total', ' Bwd IAT Mean', ' Bwd IAT Std',
       ' Bwd IAT Max', ' Bwd IAT Min', 'Fwd PSH Flags', ' Bwd PSH Flags',
       ' Fwd URG Flags', ' Bwd URG Flags', ' Fwd Header Length',
       ' Bwd Header Length', 'Fwd Packets/s', ' Bwd Packets/s',
       ' Min Packet Length', ' Max Packet Length', ' Packet Length Mean',
       ' Packet Length Std', ' Packet Length Variance', 'FIN Flag Count',
       ' SYN Flag Count', ' RST Flag Count', ' PSH Flag Count',
       ' ACK Flag Count', ' URG Flag Count', ' CWE Flag Count',
       ' ECE Flag Count', ' Down/Up Ratio', ' Average Packet Size',
       ' Avg Fwd Segment Size', ' Avg Bwd Segment Size',
       ' Fwd Header Length.1', 'Fwd Avg Bytes/Bulk', ' Fwd Avg Packets/Bulk',
       ' Fwd Avg Bulk Rate', ' Bwd Avg Bytes/Bulk', ' Bwd Avg Packets/Bulk',
       'Bwd Avg Bulk Rate', 'Subflow Fwd Packets', ' Subflow Fwd Bytes',
       ' Subflow Bwd Packets', ' Subflow Bwd Bytes', 'Init_Win_bytes_forward',
       ' Init_Win_bytes_backward', ' act_data_pkt_fwd',
       ' min_seg_size_forward', 'Active Mean', ' Active Std', ' Active Max',
       ' Active Min', 'Idle Mean', ' Idle Std', ' Idle Max', ' Idle Min',
       ' Label'],
      dtype='str')

## Data Cleaning

In [170]:
dups = data[data.duplicated()]
print(f'Number of duplicates: {len(dups)}')

Number of duplicates: 308381

In [171]:
data.drop_duplicates(inplace = True)
data.shape

(2522362, 79)

In [172]:
# Per column
(data.isnull().sum() / len(data)) * 100

# As a DataFrame
missing_data = pd.DataFrame({
    'Missing_Count': data.isnull().sum(),
    'Missing_Percent': (data.isnull().sum() / len(data)) * 100
})
missing_data

                             Missing_Count  Missing_Percent
 Destination Port                        0              0.0
 Flow Duration                           0              0.0
 Total Fwd Packets                       0              0.0
 Total Backward Packets                  0              0.0
Total Length of Fwd Packets              0              0.0
...                                    ...              ...
Idle Mean                                0              0.0
 Idle Std                                0              0.0
 Idle Max                                0              0.0
 Idle Min                                0              0.0
 Label                                   0              0.0

[79 rows x 2 columns]

In [173]:
# Clean column names first
data.columns = data.columns.str.strip()

# Now try again
med_flow_bytes = data['Flow Bytes/s'].median()
med_flow_packets = data['Flow Packets/s'].median()  # Should work now

print('Median of Flow Bytes/s:', med_flow_bytes)
print('Median of Flow Packets/s:', med_flow_packets)

Median of Flow Bytes/s: 3722.028051
Median of Flow Packets/s: 70.08936394

In [174]:
data['Flow Bytes/s'] = data['Flow Bytes/s'].fillna(med_flow_bytes)
data['Flow Packets/s'] = data['Flow Packets/s'].fillna(med_flow_packets)

In [175]:
# Clean column names first
data.columns = data.columns.str.strip()

# Now try again
med_flow_bytes = data['Flow Bytes/s'].median()
med_flow_packets = data['Flow Packets/s'].median()  # Should work now

print('Median of Flow Bytes/s:', med_flow_bytes)
print('Median of Flow Packets/s:', med_flow_packets)

Median of Flow Bytes/s: 3722.028051
Median of Flow Packets/s: 70.08936394

In [176]:
data['Flow Bytes/s'] = data['Flow Bytes/s'].fillna(med_flow_bytes)
data['Flow Packets/s'] = data['Flow Packets/s'].fillna(med_flow_packets)

In [177]:
print('Number of \'Flow Bytes/s\' missing values:', data['Flow Bytes/s'].isna().sum())
print('Number of \'Flow Packets/s\' missing values:', data['Flow Packets/s'].isna().sum())

Number of 'Flow Bytes/s' missing values: 0
Number of 'Flow Packets/s' missing values: 0

In [178]:
data['Label'].unique()

<ArrowStringArray>
[                    'BENIGN',                       'DDoS',
                   'PortScan',                        'Bot',
               'Infiltration',   'Web Attack � Brute Force',
           'Web Attack � XSS', 'Web Attack � Sql Injection',
                'FTP-Patator',                'SSH-Patator',
              'DoS slowloris',           'DoS Slowhttptest',
                   'DoS Hulk',              'DoS GoldenEye',
                 'Heartbleed']
Length: 15, dtype: str

In [179]:

# Types of attacks & normal instances (BENIGN)
data['Label'].value_counts()

Label
BENIGN                        2096484
DoS Hulk                       172849
DDoS                           128016
PortScan                        90819
DoS GoldenEye                   10286
FTP-Patator                      5933
DoS slowloris                    5385
DoS Slowhttptest                 5228
SSH-Patator                      3219
Bot                              1953
Web Attack � Brute Force         1470
Web Attack � XSS                  652
Infiltration                       36
Web Attack � Sql Injection         21
Heartbleed                         11
Name: count, dtype: int64

In [180]:
attack_map = {
    'BENIGN': 'BENIGN',
    'DDoS': 'DDoS',
    'DoS Hulk': 'DoS',
    'DoS GoldenEye': 'DoS',
    'DoS slowloris': 'DoS',
    'DoS Slowhttptest': 'DoS',
    'PortScan': 'Port Scan',
    'FTP-Patator': 'Brute Force',
    'SSH-Patator': 'Brute Force',
    'Bot': 'Bot',
    'Web Attack � Brute Force': 'Web Attack',
    'Web Attack � XSS': 'Web Attack',
    'Web Attack � Sql Injection': 'Web Attack',
    'Infiltration': 'Infiltration',
    'Heartbleed': 'Heartbleed'
}

# Creating a new column 'Attack Type' in the DataFrame based on the attack_map dictionary
data['Attack Type'] = data['Label'].map(attack_map)

In [181]:
# data['Attack Type'].value_counts()

In [182]:
# remove rare attack classes
data = data[
    ~data["Attack Type"].isin([
        "Infiltration",
        "Heartbleed",
        "Bot",
        "Web Attack"
    ])
]

# check remaining classes
print(
    data["Attack Type"].value_counts()
)

Attack Type
BENIGN         2096484
DoS             193748
DDoS            128016
Port Scan        90819
Brute Force       9152
Name: count, dtype: int64

In [183]:
# separate benign and attack
benign_data = data[
    data["Attack Type"] == "BENIGN"
]

attack_data = data[
    data["Attack Type"] != "BENIGN"
]

# keep ONLY 25k benign rows
benign_sample = benign_data.sample(
    n=200000,
    random_state=42
)

# combine with ALL attacks
data = pd.concat([

    benign_sample,

    attack_data

])

# shuffle dataset
data = data.sample(
    frac=1,
    random_state=42
)

# check result
print(
    data["Attack Type"].value_counts()
)

Attack Type
BENIGN         200000
DoS            193748
DDoS           128016
Port Scan       90819
Brute Force      9152
Name: count, dtype: int64

In [184]:
# data = data.drop(columns=["Destination Port"])

In [185]:
outlier_summary = []

for col in data.drop(columns=['Label']).select_dtypes(include=np.number).columns:

    Q1 = data[col].quantile(0.25)
    Q3 = data[col].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    percent = ((data[col] < lower) | (data[col] > upper)).mean() * 100

    outlier_summary.append([col, percent])

outlier_df = pd.DataFrame(outlier_summary, columns=["Feature", "Outlier %"])

print(outlier_df)
del outlier_df

                        Feature  Outlier %
0              Destination Port  19.583585
1                 Flow Duration   0.000000
2             Total Fwd Packets   3.988033
3        Total Backward Packets   4.298133
4   Total Length of Fwd Packets   6.514833
..                          ...        ...
73                   Active Min  18.002525
74                    Idle Mean   0.000000
75                     Idle Std   6.497945
76                     Idle Max   0.000000
77                     Idle Min   0.000000

[78 rows x 2 columns]

In [186]:
print(X.dtypes)

Flow Duration                    int64
Total Fwd Packets                int64
Total Backward Packets           int64
Total Length of Fwd Packets      int64
Total Length of Bwd Packets      int64
                                ...
Active Min                       int64
Idle Mean                      float64
Idle Std                       float64
Idle Max                         int64
Idle Min                         int64
Length: 69, dtype: object

In [187]:
# remove old binary label
data = data.drop(
    columns=['Label'],
    errors='ignore'
)

# features
X = data.drop(
    columns=['Attack Type']
)

# target
y = data['Attack Type']

In [188]:

print(np.isinf(X).sum().sum())      # total inf values
print(np.isnan(X).sum().sum())

534
0

In [189]:
X = X.replace([np.inf, -np.inf], np.nan)
X = X.fillna(X.median())

In [190]:
X = X.loc[:, X.var() != 0]

In [191]:
print(X.shape)

print(y.shape)

print(y.value_counts())

(621735, 70)
(621735,)
Attack Type
BENIGN         200000
DoS            193748
DDoS           128016
Port Scan       90819
Brute Force      9152
Name: count, dtype: int64

In [192]:
import joblib
import numpy as np

from sklearn.model_selection import train_test_split

from sklearn.preprocessing import (
    LabelEncoder,
    PowerTransformer,
    RobustScaler
)

from sklearn.pipeline import Pipeline

from sklearn.metrics import (

    accuracy_score,

    classification_report,

    confusion_matrix,

    f1_score
)

from xgboost import XGBClassifier

# ==========================================
# LABEL ENCODING
# ==========================================

encoder = LabelEncoder()

y_encoded = encoder.fit_transform(y)

# ==========================================
# TRAIN TEST SPLIT
# ==========================================

X_train, X_test, y_train, y_test = train_test_split(

    X,
    y_encoded,

    test_size=0.2,

    stratify=y_encoded,

    random_state=42
)

# ==========================================
# NUMBER OF CLASSES
# ==========================================

num_classes = len(
    np.unique(y_encoded)
)

print("Number of Classes:",
      num_classes)

print("Classes:",
      encoder.classes_)

# ==========================================
# PIPELINE
# ==========================================

model_pipeline = Pipeline([

    (
        'power',

        PowerTransformer(
            method='yeo-johnson'
        )
    ),

    (
        'scaler',

        RobustScaler()
    ),

    (
        'classifier',

        XGBClassifier(

            # multiclass
            objective='multi:softprob',

            num_class=num_classes,

            # tree params
            max_depth=6,

            learning_rate=0.1,

            n_estimators=300,

            # regularization
            reg_lambda=1,

            reg_alpha=0.5,

            # anti overfitting
            subsample=0.8,

            colsample_bytree=0.8,

            # evaluation
            eval_metric='mlogloss',

            # faster training
            tree_method='hist',

            # cpu usage
            n_jobs=-1,

            random_state=42
        )
    )
])

# ==========================================
# TRAIN MODEL
# ==========================================

print("\nTraining Started...\n")

model_pipeline.fit(
    X_train,
    y_train
)

print("\nTraining Completed\n")

# ==========================================
# PREDICTIONS
# ==========================================

y_pred = model_pipeline.predict(
    X_test
)

# ==========================================
# EVALUATION
# ==========================================

print(
    "Accuracy:",
    accuracy_score(
        y_test,
        y_pred
    )
)

print(
    "\nWeighted F1 Score:",
    f1_score(
        y_test,
        y_pred,
        average='weighted'
    )
)

print(
    "\nClassification Report:\n"
)

print(

    classification_report(

        y_test,

        y_pred,

        target_names=encoder.classes_
    )

)

print(
    "\nConfusion Matrix:\n"
)

print(
    confusion_matrix(
        y_test,
        y_pred
    )
)

# ==========================================
# SAVE PIPELINE
# ==========================================

joblib.dump(

    model_pipeline,

    "ids_multiclass_pipeline1.pkl"
)

# ==========================================
# SAVE ENCODER
# ==========================================

joblib.dump(

    encoder,

    "label_encoder1.pkl"
)

# ==========================================
# SAVE FEATURE COLUMNS
# ==========================================

joblib.dump(

    X.columns.tolist(),

    "feature_columns1.pkl"
)

print(
    "\nAll Files Saved Successfully"
)

Number of Classes: 5
Classes: ['BENIGN' 'Brute Force' 'DDoS' 'DoS' 'Port Scan']

Training Started...


Training Completed

Accuracy: 0.9996059414380725

Weighted F1 Score: 0.9996059602793027

Classification Report:

              precision    recall  f1-score   support

      BENIGN       1.00      1.00      1.00     40000
 Brute Force       1.00      1.00      1.00      1830
        DDoS       1.00      1.00      1.00     25603
         DoS       1.00      1.00      1.00     38750
   Port Scan       1.00      1.00      1.00     18164

    accuracy                           1.00    124347
   macro avg       1.00      1.00      1.00    124347
weighted avg       1.00      1.00      1.00    124347


Confusion Matrix:

[[39965     0     0    12    23]
 [    0  1830     0     0     0]
 [    2     0 25601     0     0]
 [    4     0     0 38744     2]
 [    1     0     0     5 18158]]

All Files Saved Successfully

In [194]:
# ==========================================
# GET DDoS ROWS
# ==========================================

ddos_rows = data[
    data["Attack Type"] == "DDoS"
]

# ==========================================
# SHOW SOME ROWS
# ==========================================

print(
    ddos_rows.head()
)

print(
    "\nTotal DDoS Rows:",
    len(ddos_rows)
)

        Destination Port  Flow Duration  Total Fwd Packets  \
85507                 80       82423053                  8
85482                 80       82403426                  8
107939                80       84233801                  8
39838                 80         961595                  3
114441                80       84874044                  8

        Total Backward Packets  Total Length of Fwd Packets  \
85507                        5                           56
85482                        4                           56
107939                       5                           56
39838                        6                           26
114441                       5                           56

        Total Length of Bwd Packets  Fwd Packet Length Max  \
85507                         11601                     20
85482                         11601                     20
107939                        11607                     20
39838                         11607                     20
114441                        11607                     20

        Fwd Packet Length Min  Fwd Packet Length Mean  Fwd Packet Length Std  \
85507                       0                7.000000               5.656854
85482                       0                7.000000               5.656854
107939                      0                7.000000               5.656854
39838                       0                8.666667              10.263203
114441                      0                7.000000               5.656854

        ...  min_seg_size_forward  Active Mean  Active Std  Active Max  \
85507   ...                    20    1911983.0         0.0     1911983
85482   ...                    20    1970967.0         0.0     1970967
107939  ...                    20       4990.0         0.0        4990
39838   ...                    20          0.0         0.0           0
114441  ...                    20    2111122.0         0.0     2111122

        Active Min   Idle Mean    Idle Std  Idle Max  Idle Min  Attack Type
85507      1911983  80500000.0         0.0  80500000  80500000         DDoS
85482      1970967  78700000.0         0.0  78700000  78700000         DDoS
107939        4990  42100000.0  51800000.0  78700000   5467851         DDoS
39838            0         0.0         0.0         0         0         DDoS
114441     2111122  82700000.0         0.0  82700000  82700000         DDoS

[5 rows x 79 columns]

Total DDoS Rows: 128016

In [197]:
import joblib
import pandas as pd

# ==========================================
# LOAD MODEL
# ==========================================

model = joblib.load(
    "ids_multiclass_pipeline1.pkl"
)

# ==========================================
# LOAD ENCODER
# ==========================================

encoder = joblib.load(
    "label_encoder1.pkl"
)

# ==========================================
# LOAD FEATURE COLUMNS
# ==========================================

feature_columns = joblib.load(
    "feature_columns1.pkl"
)

# ==========================================
# TAKE REAL DDoS SAMPLE
# ==========================================

sample = data[
    data["Attack Type"] == "DDoS"
].iloc[[0]]

# ==========================================
# REMOVE TARGET
# ==========================================

X_sample = sample.drop(
    columns=["Attack Type"]
)

# ==========================================
# KEEP ONLY TRAINED FEATURES
# ==========================================

X_sample = X_sample[
    feature_columns
]

# ==========================================
# PREDICT
# ==========================================

prediction = model.predict(
    X_sample
)

# ==========================================
# PROBABILITIES
# ==========================================

probabilities = model.predict_proba(
    X_sample
)

# ==========================================
# DECODE LABEL
# ==========================================

predicted_label = (
    encoder.inverse_transform(
        prediction
    )
)

# ==========================================
# RESULTS
# ==========================================

print(
    "Actual Label:",
    sample["Attack Type"].values[0]
)

print(
    "Predicted Label:",
    predicted_label[0]
)

print("\nProbabilities:\n")

for cls, prob in zip(

    encoder.classes_,

    probabilities[0]
):

    print(
        f"{cls}: {prob:.4f}"
    )

Actual Label: DDoS
Predicted Label: DDoS

Probabilities:

BENIGN: 0.0000
Brute Force: 0.0000
DDoS: 1.0000
DoS: 0.0000
Port Scan: 0.0000

In [205]:
# ==========================================
# FETCH 30 ROWS FROM EACH CLASS
# ==========================================

live_attack = (

    data.groupby("Attack Type")

    .apply(
        lambda x: x.sample(
            30,
            random_state=42
        )
    )

    .reset_index(drop=True)

)

# ==========================================
# SHUFFLE DATA
# ==========================================

live_attack = live_attack.sample(

    frac=1,

    random_state=42

).reset_index(drop=True)

# ==========================================
# SAVE CSV
# ==========================================

live_attack.to_csv(

    "live_attack.csv",

    index=False
)

# ==========================================
# CHECK RESULT
# ==========================================

print(
    live_attack["Attack Type"]
    .value_counts()
)

print(
    "\nTotal Rows:",
    len(live_attack)
)

print(
    "\nlive_attack.csv saved successfully"
)

KeyError: 'Attack Type'